Updates googletest
due to compile error locally:

```
FAILED: googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
sccache /usr/bin/c++ -DBOOST_NO_CXX11_SCOPED_ENUMS -DDATA_TOOLS -DGTEST_CREATE_SHARED_LIBRARY=1 -Dgtest_EXPORTS -I../third_party/googletest/googletest/include -I../third_party/googletest/googletest -fdiagnostics-color=auto  -g -fPIC -Wall -Wshadow -Werror -Wno-error=dangling-else -DGTEST_HAS_PTHREAD=1 -fexceptions -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -pthread -std=c++11 -MD -MT googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o -MF googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o.d -o googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o -c ../third_party/googletest/googletest/src/gtest-all.cc
In file included from ../third_party/googletest/googletest/src/gtest-all.cc:42:
../third_party/googletest/googletest/src/gtest-death-test.cc: In function ‘bool testing::internal::StackGrowsDown()’:
../third_party/googletest/googletest/src/gtest-death-test.cc:1301:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]
 1301 |   StackLowerThanAddress(&dummy, &result);
      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
../third_party/googletest/googletest/src/gtest-death-test.cc:1290:13: note: by argument 1 of type ‘const void*’ to ‘void testing::internal::StackLowerThanAddress(const void*, bool*)’ declared here
 1290 | static void StackLowerThanAddress(const void* ptr, bool* result) {
      |             ^~~~~~~~~~~~~~~~~~~~~
../third_party/googletest/googletest/src/gtest-death-test.cc:1299:7: note: ‘dummy’ declared here
 1299 |   int dummy;
      |       ^~~~~
cc1plus: all warnings being treated as errors
[49/867] Compile locale definition files...
ninja: build stopped: subcommand failed.
```