Fixes missing stdint include
causing error

```
../valhalla/midgard/point2.h:198:5: error: ‘uint64_t’ was not declared in this scope; did you mean ‘u_int64_t’?
```