Fix float to odin::DirectionsOptions::DateTimeType enum conversion
MSVC 19.15 issues error C2440: static_cast: cannot convert from T to DateTimeType
due to conversions between enumeration and floating point values are no
longer allowed.

Fixes #1626