Fix Conan ERROR
-------------------------------------
-- Conan: checking conan executable
-- Conan: Found program /usr/local/bin/conan
-- Conan: Version found Conan version 1.43.0
-- Conan executing: /usr/local/bin/conan install /usr/local/src/valhalla/conanfile.txt --remote conancenter --settings build_type=RelWithDebInfo --settings compiler=gcc --settings compiler.version=9 --settings compiler.libcxx=libstdc++11 --settings compiler.cppstd=14
ERROR: Not able to automatically detect '/usr/bin/cc' version
ERROR: Unable to find a working compiler
WARN: Remotes registry file missing, creating default one in /root/.conan/remotes.json
-- Conan: Using autogenerated FindBoost.cmake
-------------------------------------