Add maybe_unused attribute to found variable
This was providing a similar error as before:
 error: variable 'found' set but not used [-Werror,-Wunused-but-set-variable]
As the variable is only used when the logging level is set to trace.