Mode filters (#1642)
* add resize_file and create_directories (#1591)

* add resize_file and create_directories

* Remove log bd (#1609)

* Change LOG_INFO to LOG_DEBUG for path cost and iteration count. Inadvertently
was changed on earlier commit/merge.

* Fix formatting

* hardening for file name to graphid (#1612)

* A timed-turned restriction should not be applied when a non-timed route is executed. (#1615)

* If a user runs a non-time dependent route, then time-dep restrictions should not be enforced.

* added more test cases.

* format

* updated.

* Adjusted dest point of one test

* Add CMakeSettings.json with reasonable defaults [ci skip] (#1606)

CMakeSettings.json is convenient to control build configuration
when using CMake integration with Visual Studio 2017.
Usage:
 - Copy cmake/CMakeSettings.json to top-level directory of
   Valhalla source tree
 - In VS2017 > File > Open > CMake > select top-level CMakeLists.txt
 - Edit CMakeSettings.json, flip options, add options for dependencies, etc.

Ignore user-speciifc local directory managed by CLion IDE.

* Fix float to odin::DirectionsOptions::DateTimeType enum conversion (#1627)

MSVC 19.15 issues error C2440: static_cast: cannot convert from T to DateTimeType
due to conversions between enumeration and floating point values are no
longer allowed.

Fixes #1626

* Update filesystem.h to support compilation with MSVC (#1629)

Use _mkdir from UCRT subset of POSIX compatibility routines.
Add internal truncate implemented in terms of UCRT _chsize
as equivalent of POSIX function.

Follows #1466

* Fix warnings about redefinition of MSVC macros defined in sequence.h (#1628)

The macros are also controlled by CMake configuration, so perhaps they
can be removed completely.

* Fix transition penalties for bicycle costing. Missed adding penalty when ported to return a Cost structure. (#1636)

* Fix comment

* Add GraphFilter and config options to filter/remove edges for specific access modes. This
is a new stage of the Valhalla tile generation process. It occurs after GraphEnhancer.
This should allow the long running stages (parsing, tile building, enhancement) to be done
once and the cut different tile versions with different filtering, hierarchy generation,
presence of transit and traffic.

* Check that node has transitions before getting the first transition node from the tile.

* Update log messages in GraphFilter.